####################################################################################################
# config
####################################################################################################

goapp := 'Lilith'
goexe := 'lilith'
dir := '.lilith'
forge := dir / 'forge'
interpret := dir / 'interpret'
config := dir / 'config'

####################################################################################################
