[workflows.helix]
watch  = "~/.archive/ex-situ/helix/modes"
script = "~/.lilith/sh/helix.sh"

[workflows.language]
watch = "~/.archive/ex-situ/helix/languages"
script = "~/.lilith/sh/language.sh"

[workflows.goku]
watch  = "~/.saiyajin/frag"
script = "~/.lilith/sh/goku.sh"
