[workflows.helix]
watch  = "~/.archive/ex-situ/helix/modes"
script = "~/.lilith/sh/helix.sh"
log    = "helix"

[workflows.goku]
watch  = "~/.saiyajin/frag"
script = "~/.lilith/sh/goku.sh"
log    = "goku"
