[workflows.alacritty]
watch = "~/.config/alacritty/alacritty.yml"
script = "~/.lilith/forge/alacritty.sh"

[workflows.helix]
watch = "~/lab/dotfiles/ex-situ/helix/modes"
script = "~/.lilith/forge/helix.sh"

[workflows.language]
watch = "~/lab/dotfiles/ex-situ/helix/languages"
script = "~/.lilith/forge/language.sh"

[workflows.goku]
watch = "~/lab/Saiya-jin/src"
script = "~/.lilith/forge/goku.sh"

[workflows.zellij]
watch = "~/lab/dotfiles/in-situ/zellij/modes"
script = "~/.lilith/forge/zellij.sh"
