[workflows.helix]
watch = "~/Factorem/dotfiles/ex-situ/helix/modes"
script = "~/.lilith/forge/helix.sh"

[workflows.language]
watch = "~/Factorem/dotfiles/ex-situ/helix/languages"
script = "~/.lilith/forge/language.sh"

[workflows.goku]
watch = "~/.saiyajin/frag"
script = "~/.lilith/forge/goku.sh"

[workflows.alacritty]
watch = "~/.config/alacritty/alacritty.toml"
script = "~/.lilith/forge/alacritty.sh"
