[workflows.helix]
watch = "~/lab/Saiya-jin/karabiner/karabiner.edn"
script = "~/.lilith/interpret/helix.sh"

[workflows.micro]
watch = "~/lab/Saiya-jin/karabiner/karabiner.edn"
script = "~/.lilith/interpret/micro.sh"
