[workflows.interpret-helix]
watch = "~/Factorem/Saiya-jin/karabiner/karabiner.edn"
script = "~/.lilith/interpret/helix.sh"

[workflows.interpret-micro]
watch = "~/Factorem/Saiya-jin/karabiner/karabiner.edn"
script = "~/.lilith/interpret/micro.sh"
